# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaRespondida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestaapp.Encuesta')),
            ],
        ),
    ]
